[build]
  publish = "frontend"
  command = ""

[[redirects]]
  # Route any /api calls to our Render backend (update the URL when generated)
  # from = "/api/*"
  # to = "https://your-render-url.onrender.com/api/:splat"
  # status = 200
  # force = true

[[redirects]]
  # Ensure normal routing for our SPA
  from = "/*"
  to = "/index.html"
  status = 200
