[build]
  publish = "frontend"
  command = ""

[functions]
  included_files = ["backend/**"]
  # Setting directory for Netlify Python functions
  directory = "netlify/functions"

[[redirects]]
  # Route any /api calls to our serverless backend
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  # Ensure normal routing for our SPA
  from = "/*"
  to = "/index.html"
  status = 200
